export const CUSTOMER_GET_LIST_REQ = '@CUSTOMER/CUSTOMER_GET_LIST_REQ';
export const CUSTOMER_GET_LIST_SUCCESS = '@CUSTOMER/CUSTOMER_GET_LIST_SUCCESS';
export const CUSTOMER_GET_LIST_FAIL = '@CUSTOMER/CUSTOMER_GET_LIST_FAIL';

export const CUSTOMER_CREATE_REQ = '@CUSTOMER/CUSTOMER_CREATE_REQ';
export const CUSTOMER_CREATE_SUCCESS = '@CUSTOMER/CUSTOMER_CREATE_SUCCESS';
export const CUSTOMER_CREATE_FAIL = '@CUSTOMER/CUSTOMER_CREATE_FAIL';
export const CUSTOMER_CREATE_CLEAR = '@CUSTOMER/CUSTOMER_CREATE_CLEAR';

export const CUSTOMER_UPDATE_REQ = '@CUSTOMER/CUSTOMER_UPDATE_REQ';
export const CUSTOMER_UPDATE_SUCCESS = '@CUSTOMER/CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_FAIL = '@CUSTOMER/CUSTOMER_UPDATE_FAIL';
export const CUSTOMER_UPDATE_CLEAR = '@CUSTOMER/CUSTOMER_UPDATE_CLEAR';

export const CUSTOMER_DELETE_REQ = '@CUSTOMER/CUSTOMER_DELETE_REQ';
export const CUSTOMER_DELETE_SUCCESS = '@CUSTOMER/CUSTOMER_DELETE_SUCCESS';
export const CUSTOMER_DELETE_FAIL = '@CUSTOMER/CUSTOMER_DELETE_FAIL';
export const CUSTOMER_DELETE_CLEAR = '@CUSTOMER/CUSTOMER_DELETE_CLEAR';