export const QUOTATION_GET_LIST_REQ = '@QUOTATION/QUOTATION_GET_LIST_REQ';
export const QUOTATION_GET_LIST_SUCCESS = '@QUOTATION/QUOTATION_GET_LIST_SUCCESS';
export const QUOTATION_GET_LIST_FAIL = '@QUOTATION/QUOTATION_GET_LIST_FAIL';


export const QUOTATION_CREATE_REQ = '@QUOTATION/QUOTATION_CREATE_REQ';
export const QUOTATION_CREATE_SUCCESS = '@QUOTATION/QUOTATION_CREATE_SUCCESS';
export const QUOTATION_CREATE_FAIL = '@QUOTATION/QUOTATION_CREATE_FAIL';
export const QUOTATION_CREATE_CLEAR = '@QUOTATION/QUOTATION_CREATE_CLEAR';