export const QUOTATION_GET_LIST_REQ = '@QUOTATION/QUOTATION_GET_LIST_REQ';
export const QUOTATION_GET_LIST_SUCCESS = '@QUOTATION/QUOTATION_GET_LIST_SUCCESS';
export const QUOTATION_GET_LIST_FAIL = '@QUOTATION/QUOTATION_GET_LIST_FAIL';


export const QUOTATION_CREATE_REQ = '@QUOTATION/QUOTATION_CREATE_REQ';
export const QUOTATION_CREATE_SUCCESS = '@QUOTATION/QUOTATION_CREATE_SUCCESS';
export const QUOTATION_CREATE_FAIL = '@QUOTATION/QUOTATION_CREATE_FAIL';
export const QUOTATION_CREATE_CLEAR = '@QUOTATION/QUOTATION_CREATE_CLEAR';

export const QUOTATION_UPDATE_REQ = '@QUOTATION/QUOTATION_UPDATE_REQ';
export const QUOTATION_UPDATE_SUCCESS = '@QUOTATION/QUOTATION_UPDATE_SUCCESS';
export const QUOTATION_UPDATE_FAIL = '@QUOTATION/QUOTATION_UPDATE_FAIL';
export const QUOTATION_UPDATE_CLEAR = '@QUOTATION/QUOTATION_UPDATE_CLEAR';

export const QUOTATION_EXPORT_REQ = '@QUOTATION/QUOTATION_EXPORT_REQ';
export const QUOTATION_EXPORT_SUCCESS = '@QUOTATION/QUOTATION_EXPORT_SUCCESS';
export const QUOTATION_EXPORT_FAIL = '@QUOTATION/QUOTATION_EXPORT_FAIL';

export const QUOTATION_DELETE_REQ = '@QUOTATION/QUOTATION_DELETE_REQ';
export const QUOTATION_DELETE_SUCCESS = '@QUOTATION/QUOTATION_DELETE_SUCCESS';
export const QUOTATION_DELETE_FAIL = '@QUOTATION/QUOTATION_DELETE_FAIL';
export const QUOTATION_DELETE_CLEAR = '@QUOTATION/QUOTATION_DELETE_CLEAR';