export const COMPANY_GET_GENERAL_INFO_REQ = '@DASHBOARD/COMPANY_GET_GENERAL_INFO_REQ';
export const COMPANY_GET_GENERAL_INFO_SUCCESS = '@DASHBOARD/COMPANY_GET_GENERAL_INFO_SUCCESS';
export const COMPANY_GET_GENERAL_INFO_FAIL = '@DASHBOARD/COMPANY_GET_GENERAL_INFO_FAIL';

export const CUSTOMER_GET_GENERAL_INFO_REQ = '@DASHBOARD/CUSTOMER_GET_GENERAL_INFO_REQ';
export const CUSTOMER_GET_GENERAL_INFO_SUCCESS = '@DASHBOARD/CUSTOMER_GET_GENERAL_INFO_SUCCESS';
export const CUSTOMER_GET_GENERAL_INFO_FAIL = '@DASHBOARD/CUSTOMER_GET_GENERAL_INFO_FAIL';

export const INVOICE_GET_GENERAL_INFO_REQ = '@DASHBOARD/INVOICE_GET_GENERAL_INFO_REQ';
export const INVOICE_GET_GENERAL_INFO_SUCCESS = '@DASHBOARD/INVOICE_GET_GENERAL_INFO_SUCCESS';
export const INVOICE_GET_GENERAL_INFO_FAIL = '@DASHBOARD/INVOICE_GET_GENERAL_INFO_FAIL';