export const INVOICE_GET_LIST_REQ = '@INVOICE/INVOICE_GET_LIST_REQ';
export const INVOICE_GET_LIST_SUCCESS = '@INVOICE/INVOICE_GET_LIST_SUCCESS';
export const INVOICE_GET_LIST_FAIL = '@INVOICE/INVOICE_GET_LIST_FAIL';

export const INVOICE_CREATE_REQ = '@INVOICE/INVOICE_CREATE_REQ';
export const INVOICE_CREATE_SUCCESS = '@INVOICE/INVOICE_CREATE_SUCCESS';
export const INVOICE_CREATE_FAIL = '@INVOICE/INVOICE_CREATE_FAIL';
export const INVOICE_CREATE_CLEAR = '@INVOICE/INVOICE_CREATE_CLEAR';

export const INVOICE_UPDATE_REQ = '@INVOICE/INVOICE_UPDATE_REQ';
export const INVOICE_UPDATE_SUCCESS = '@INVOICE/INVOICE_UPDATE_SUCCESS';
export const INVOICE_UPDATE_FAIL = '@INVOICE/INVOICE_UPDATE_FAIL';
export const INVOICE_UPDATE_CLEAR = '@INVOICE/INVOICE_UPDATE_CLEAR';

export const INVOICE_DELETE_REQ = '@INVOICE/INVOICE_DELETE_REQ';
export const INVOICE_DELETE_SUCCESS = '@INVOICE/INVOICE_DELETE_SUCCESS';
export const INVOICE_DELETE_FAIL = '@INVOICE/INVOICE_DELETE_FAIL';
export const INVOICE_DELETE_CLEAR = '@INVOICE/INVOICE_DELETE_CLEAR';

export const INVOICE_GET_LATEST_REQ = '@INVOICE/INVOICE_GET_LATEST_REQ';
export const INVOICE_GET_LATEST_SUCCESS = '@INVOICE/INVOICE_GET_LATEST_SUCCESS';
export const INVOICE_GET_LATEST_FAIL = '@INVOICE/INVOICE_GET_LATEST_FAIL';