export const AUTHEN_LOGIN_REQ = '@AUTHEN/AUTHEN_LOGIN_REQ';
export const AUTHEN_LOGIN_SUCCESS = '@AUTHEN/AUTHEN_LOGIN_SUCCESS';
export const AUTHEN_LOGIN_FAIL = '@AUTHEN/AUTHEN_LOGIN_FAIL';

export const AUTHEN_GET_CURRENT_REQ = '@AUTHEN/AUTHEN_GET_CURRENT_REQ';
export const AUTHEN_GET_CURRENT_SUCCESS = '@AUTHEN/AUTHEN_GET_CURRENT_SUCCESS';
export const AUTHEN_GET_CURRENT_FAIL = '@AUTHEN/AUTHEN_GET_CURRENT_FAIL';
export const AUTHEN_GET_CURRENT_CLEAR = '@AUTHEN/AUTHEN_GET_CURRENT_CLEAR';
