export const COMPANY_CREATE_REQ = '@COMPANY/COMPANY_CREATE_REQ';
export const COMPANY_CREATE_SUCCESS = '@COMPANY/COMPANY_CREATE_SUCCESS';
export const COMPANY_CREATE_FAIL = '@COMPANY/COMPANY_CREATE_FAIL';

export const COMPANY_GET_LIST_REQ = '@COMPANY/COMPANY_GET_LIST_REQ';
export const COMPANY_GET_LIST_SUCCESS = '@COMPANY/COMPANY_GET_LIST_SUCCESS';
export const COMPANY_GET_LIST_FAIL = '@COMPANY/COMPANY_GET_LIST_FAIL';

